### ISSUE TITLE
2.0-2 breaks dnf upgrade --security on AlmaLinux 8.9

### ISSUE THREAD

**Issue by hakonhall** [NVIDIA/yum-packaging-nvidia-plugin#12]
Running `dnf upgrade --security` on AlmaLinux 8.9, after

```
$ dnf config-manager --add-repo=https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
$ dnf config-manager --set-disabled cuda-rhel8-x86_64
$ dnf module install -y --enablerepo cuda-rhel8-x86_64 nvidia-driver:545
```

fails with

```
AlmaLinux 8 - BaseOS                            4.5 MB/s | 8.3 MB     00:01
AlmaLinux 8 - AppStream                         8.8 MB/s |  13 MB     00:01
AlmaLinux 8 - Extras                             30 kB/s |  21 kB     00:00
Error:
WARNING: kernel exclude error local variable 'kmod_pkg_name' referenced before assignment
 Problem: package kernel-modules-4.18.0-513.24.1.el8_9.x86_64 from baseos requires kernel-uname-r = 4.18.0-513.24.1.el8_9.x86_64, but none of the providers can be installed
WARNING: kernel exclude error local variable 'kmod_pkg_name' referenced before assignment
  - cannot install the best update candidate for package kernel-modules-4.18.0-513.18.1.el8_9.x86_64
  - package kernel-core-4.18.0-513.24.1.el8_9.x86_64 from baseos is filtered out by exclude filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

If I downgrade dnf-plugin-nvidia from 2.0-2 to 2.0-1, the `dnf upgrade --security` command succeeds, although dnf-plugin-nvidia prints the error reported in #10.

So `dnf upgrade --security` wants to upgrade or resolve `kernel-modules-4.18.0-513.24.1.el8_9.x86_64`, which requires exactly the same version of `kernel-core`, but dnf-plugin-nvidia has excluded the latter?

**Comment by scaronni-nvidia** [comment]
@hakonhall  the plugin has been updated (version 2.1-2) and along with a regenerated modules metadata on the repository there are now quite a few changes.

For the plugin, the kernel subpackages are considered as part of the blacklist, only the relevant precompiled kernel module is considered, all DNF operations are takien into account (downgrade, security updates, etc).).

For the metadata, all the kernel module packages (proprietary precompiled, proprietary DKMS and open DKMS) are now inside the appropriate DNF module streams and don't pop in randomly into the resolution of dependencies due to them being outside of the stream.

Please test again and open another bug if you see additional issues. Thanks!

**Comment by hakonhall** [comment]
@scaronni-nvidia , thank you, this has fixed the issue for us.
