### ISSUE TITLE
this dnf-plugin does not stop the kernel update as described in the blog

### ISSUE THREAD

**Issue by braindevices** [NVIDIA/yum-packaging-nvidia-plugin#8]
[here](https://developer.nvidia.com/blog/streamlining-nvidia-driver-deployment-on-rhel-8-with-modularity-streams/) said:
> To prevent system breakages, the dnf plugin blocks kernel updates between a kernel going live and kmod package availability. 

this mechanism seems broken and leave the system without proper kmod. I tried on VMs several times:
1. I boot a server with older kernel and installed with nvidia-driver:
```
# dnf list installed | grep kernel
abrt-addon-kerneloops.x86_64                 2.10.9-21.el8.alma                                 @appstream             
kernel.x86_64                                4.18.0-348.12.2.el8_5                              @anaconda              
kernel-core.x86_64                           4.18.0-348.12.2.el8_5                              @anaconda              
kernel-devel.x86_64                          4.18.0-348.12.2.el8_5                              @baseos                
kernel-headers.x86_64                        4.18.0-348.12.2.el8_5                              @baseos                
kernel-modules.x86_64                        4.18.0-348.12.2.el8_5                              @anaconda              
kernel-tools.x86_64                          4.18.0-348.12.2.el8_5                              @anaconda              
kernel-tools-libs.x86_64                     4.18.0-348.12.2.el8_5                              @anaconda

# dnf list installed | grep kmod-nvidia
kmod-nvidia-510.47.03-4.18.0-348.12.2.x86_64 3:510.47.03-3.el8_5                                @cuda-rhel8-x86_64

# dnf list installed | grep nvidia
dnf-plugin-nvidia.noarch                     2.0-1.el8
```
2. then I do a `dnf update`:
```
Installed:
  kernel-4.18.0-348.23.1.el8_5.x86_64                          kernel-core-4.18.0-348.23.1.el8_5.x86_64                      
  kernel-devel-4.18.0-348.23.1.el8_5.x86_64                    kernel-modules-4.18.0-348.23.1.el8_5.x86_64 

# dnf list installed | grep kmod-nvidia
kmod-nvidia-510.47.03-4.18.0-348.12.2.x86_64 3:510.47.03-3.el8_5                                @cuda-rhel8-x86_64
```
We can see the new kernel are installed and no kmod available for it.

**Comment by braindevices** [comment]
there is a bug in the `NvidiaPlugin.sack()` It does not map the kernel-driver pair, instead it put all kmod_pkg for all available kernel updates together. Thus, if there is only single available kernel candidates. It can work. Howerver, in this case there are several kernel updates 348.20.1 and 348.23.1. Because the kmod for 348.20.1 does exist, it allows the update of kernel.

**Comment by scaronni-nvidia** [comment]
@braindevices the plugin has been updated (version 2.1-2) and along with a regenerated modules metadata on the repository there are now quite a few changes.

For the plugin, the kernel subpackages are considered as part of the blacklist, only the relevant precompiled kernel module is considered, all DNF operations are takien into account (downgrade, security updates, etc).).

For the metadata, all the kernel module packages (proprietary precompiled, proprietary DKMS and open DKMS) are now inside the appropriate DNF module streams and don't pop in randomly into the resolution of dependencies due to them being outside of the stream.

Please test again and open another bug if you see additional issues. Thanks!
